In [1]:
import numpy as np
import tensorflow as tf
from tensorflow.keras.datasets import imdb
from tensorflow.keras.preprocessing import sequence
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding,SimpleRNN,Dense
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [3]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [4]:
voc_size = 10000

In [5]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [6]:
one_hot_rep = [one_hot(words, voc_size)for words in sent]
one_hot_rep


[[8126, 3502, 2409, 6303],
 [8126, 3502, 2409, 88],
 [8126, 7046, 2409, 9915],
 [9437, 7336, 5894, 5594, 164],
 [9437, 7336, 5894, 5594, 2019],
 [9274, 8126, 6079, 2409, 3695],
 [5093, 5590, 7173, 5594]]

In [7]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential
import numpy as np 


In [8]:
sent_length = 8
embedding_doc = pad_sequences(one_hot_rep,padding='pre',maxlen=sent_length)
embedding_doc

array([[   0,    0,    0,    0, 8126, 3502, 2409, 6303],
       [   0,    0,    0,    0, 8126, 3502, 2409,   88],
       [   0,    0,    0,    0, 8126, 7046, 2409, 9915],
       [   0,    0,    0, 9437, 7336, 5894, 5594,  164],
       [   0,    0,    0, 9437, 7336, 5894, 5594, 2019],
       [   0,    0,    0, 9274, 8126, 6079, 2409, 3695],
       [   0,    0,    0,    0, 5093, 5590, 7173, 5594]])

In [9]:
dim = 10
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam', 'mse')

In [10]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 8, 10)             100000    
                                                                 
Total params: 100000 (390.62 KB)
Trainable params: 100000 (390.62 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [11]:
model.predict(embedding_doc)

1/1 [==============================] - 0s 100ms/step


array([[[ 0.02102245,  0.0091838 ,  0.0315843 , -0.00864691,
          0.0420512 , -0.01888497,  0.01915387, -0.02482873,
         -0.03817904, -0.02400932],
        [ 0.02102245,  0.0091838 ,  0.0315843 , -0.00864691,
          0.0420512 , -0.01888497,  0.01915387, -0.02482873,
         -0.03817904, -0.02400932],
        [ 0.02102245,  0.0091838 ,  0.0315843 , -0.00864691,
          0.0420512 , -0.01888497,  0.01915387, -0.02482873,
         -0.03817904, -0.02400932],
        [ 0.02102245,  0.0091838 ,  0.0315843 , -0.00864691,
          0.0420512 , -0.01888497,  0.01915387, -0.02482873,
         -0.03817904, -0.02400932],
        [-0.04011182, -0.01039974, -0.0356583 ,  0.04340384,
          0.00546188,  0.02790104,  0.04529095, -0.03922485,
          0.02049426, -0.02178033],
        [-0.03312286,  0.02123574, -0.01320865, -0.01204131,
          0.01889253, -0.02241687,  0.00542054, -0.02583265,
          0.00906588, -0.04452939],
        [ 0.036223  , -0.02927344,  0.0216619 , -0.0

In [12]:
embedding_doc[0]

array([   0,    0,    0,    0, 8126, 3502, 2409, 6303])

In [13]:
model.predict(embedding_doc[0])

1/1 [==============================] - 0s 48ms/step


array([[ 0.02102245,  0.0091838 ,  0.0315843 , -0.00864691,  0.0420512 ,
        -0.01888497,  0.01915387, -0.02482873, -0.03817904, -0.02400932],
       [ 0.02102245,  0.0091838 ,  0.0315843 , -0.00864691,  0.0420512 ,
        -0.01888497,  0.01915387, -0.02482873, -0.03817904, -0.02400932],
       [ 0.02102245,  0.0091838 ,  0.0315843 , -0.00864691,  0.0420512 ,
        -0.01888497,  0.01915387, -0.02482873, -0.03817904, -0.02400932],
       [ 0.02102245,  0.0091838 ,  0.0315843 , -0.00864691,  0.0420512 ,
        -0.01888497,  0.01915387, -0.02482873, -0.03817904, -0.02400932],
       [-0.04011182, -0.01039974, -0.0356583 ,  0.04340384,  0.00546188,
         0.02790104,  0.04529095, -0.03922485,  0.02049426, -0.02178033],
       [-0.03312286,  0.02123574, -0.01320865, -0.01204131,  0.01889253,
        -0.02241687,  0.00542054, -0.02583265,  0.00906588, -0.04452939],
       [ 0.036223  , -0.02927344,  0.0216619 , -0.04100369, -0.03440901,
        -0.00080296,  0.01428893,  0.0174466 

In [14]:
import numpy as np 
import pandas as pd 
import tensorflow as tf
from tensorflow.keras.models import load_model
from tensorflow.keras.datasets import imdb
from tensorflow.keras.preprocessing import sequence

In [15]:
word_idx=imdb.get_word_index()
reverse_word_idx={value:key for key, value in word_idx.items()}

In [16]:
model = load_model('simple_rnn_imdb.h5')
model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_1 (Embedding)     (None, 500, 128)          1280000   
                                                                 
 simple_rnn_1 (SimpleRNN)    (None, 128)               32896     
                                                                 
 dense_1 (Dense)             (None, 1)                 129       
                                                                 
Total params: 1313025 (5.01 MB)
Trainable params: 1313025 (5.01 MB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [17]:
model.get_weights()

[array([[ 0.01294318,  0.00555024, -0.07671961, ..., -0.01263755,
          0.00505546,  0.02497914],
        [ 0.00844798, -0.02933332, -0.00715619, ..., -0.00862716,
          0.00665992,  0.05880589],
        [-0.05171771, -0.0432808 , -0.08375057, ..., -0.02969957,
          0.01567038,  0.00068079],
        ...,
        [ 0.09266458, -0.08101614,  0.04658744, ...,  0.01804913,
         -0.17538679,  0.00067434],
        [ 0.01653318,  0.06926119,  0.0049732 , ...,  0.04035291,
          0.09395951, -0.1132597 ],
        [ 0.1440855 ,  0.00126064,  0.32376543, ...,  0.0426919 ,
          0.02079754, -0.18269144]], dtype=float32),
 array([[-0.12330135,  0.08859511,  0.05113527, ...,  0.03298575,
          0.17755416,  0.01216303],
        [-0.04188077, -0.04186596, -0.08071131, ...,  0.15609226,
         -0.07695719,  0.02690291],
        [-0.00996152, -0.11690302, -0.03616346, ...,  0.05564096,
          0.10746004,  0.16173892],
        ...,
        [-0.04128347, -0.12895729, -0.0

In [18]:
def decode_review(encoded_review):
    return ' '.join(reverse_word_idx.get(i - 3, '?') for i in encoded_review)

def preprocess_text(text):
    words = text.lower().split()
    encoded_review = [word_idx.get(word, 2) + 3 for word in words]
    padded_seq = sequence.pad_sequences([encoded_review], maxlen=500)
    return padded_seq



In [19]:
def prediction_sent(review):
    preprocessed_text = preprocess_text(review)
    prediction=model.predict(preprocessed_text)
    sentement = 'Positive' if prediction[0][0]  > 0.5 else 'Negative'
    return sentement, prediction[0][0]

In [20]:
example_review = "This movie was fantastic! The acting was great and the plot was thrilling."

sentement,score=prediction_sent(example_review)
print(f"Review: {example_review}")
print(f"Sentement: {sentement}")
print(f"Score: {score}")

1/1 [==============================] - 0s 223ms/step
Review: This movie was fantastic! The acting was great and the plot was thrilling.
Sentement: Positive
Score: 0.8114995360374451
